name: assignment9
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intro_slider: ^2.4.3
  video_player: ^2.1.5
  video_player_web: ^2.0.1
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/dp.jpg
    - assets/prime-and-composite-numbers-l.jpg
    - assets/images.png
    - assets/Flutter-Widgets.png
    - assets/ico.jpg
    - assets/i.jpg
    - assets/w.png
    - assets/App-Development.jpg
    - assets/Development.jpg
    - assets/Ass1.mp4
    - assets/Ass2.mp4
    - assets/Ass3.mp4
    - assets/Ass4.mp4
    - assets/Ass5.mp4
    - assets/Ass6.mp4
    - assets/Ass7.mp4
   # - assets/Ass1.mp4


    - assets/Ass1/Ass11.PNG
    - assets/Ass1/Ass12.PNG
    - assets/Ass1/Ass13.PNG
    - assets/Ass1/Ass14.PNG
    - assets/Ass1/Ass15.PNG

    - assets/Ass2/Ass21.PNG
    - assets/Ass2/Ass22.PNG

    - assets/Ass3/Ass31.PNG
    - assets/Ass3/Ass32.PNG

    - assets/Ass4/Ass41.PNG
    - assets/Ass4/Ass42.PNG
    - assets/Ass4/Ass43.PNG
    - assets/Ass4/Ass44.PNG
    - assets/Ass4/Ass45.PNG
    - assets/Ass4/Ass46.PNG
    - assets/Ass4/Assignment.png

    - assets/Ass5/Ass51.PNG
    - assets/Ass5/Ass52.PNG
    - assets/Ass5/Ass53.PNG
    - assets/Ass5/Ass54.PNG
    - assets/Ass5/Ass55.PNG
    - assets/Ass5/Ass56.PNG

    - assets/Ass6/Ass61.PNG
    - assets/Ass6/Ass62.PNG
    - assets/Ass6/Ass63.PNG
    - assets/Ass6/Ass64.PNG
    - assets/Ass6/Ass65.PNG
    - assets/Ass6/Ass66.PNG
    - assets/Ass6/Ass67.PNG
    - assets/Ass6/Ass68.PNG
    - assets/Ass6/Ass69.PNG

    - assets/Ass7/Ass71.PNG
    - assets/Ass7/Ass72.PNG
    - assets/Ass7/Ass73.PNG
    - assets/Ass7/Ass74.PNG
    - assets/Ass7/Ass75.PNG
    - assets/Ass7/Ass76.PNG
    - assets/Ass7/Ass77.PNG
    - assets/Ass7/Ass78.PNG
    - assets/Ass7/Ass79.PNG

    - assets/Ass8/Ass11.PNG
    - assets/Ass8/Ass12.PNG
    - assets/Ass8/Ass13.PNG
    - assets/Ass8/Ass14.PNG
    - assets/Ass8/Ass15.PNG
    - assets/Ass8/Ass16.PNG
    - assets/Ass8/Ass17.PNG
    - assets/Ass8/Ass10.PNG
    - assets/Ass8/Ass81.PNG
    - assets/Ass8/Ass82.PNG
    - assets/Ass8/Ass83.PNG
    - assets/Ass8/Ass84.PNG
    - assets/Ass8/Ass85.PNG
    - assets/Ass8/Ass86.PNG
    - assets/Ass8/Ass87.PNG
    - assets/Ass8/Ass88.PNG
    - assets/Ass8/Ass89.PNG
    - assets/Ass8/Ass91.PNG
    - assets/Ass8/Ass92.PNG
    - assets/Ass8/Ass93.PNG
    - assets/Ass8/Ass94.PNG
    - assets/Ass8/Ass95.PNG
    - assets/Ass8/Ass96.PNG
    - assets/Ass8/Ass98.PNG
    - assets/Ass8/Ass99.PNG
    - assets/Ass8/Ass90.PNG



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
